### PR TITLE
add HIGH SensitivityWatchEventModifier to register call

### PR DESCRIPTION
**Pull request by mdpendergrass**
for improved performance on Mac OS/X

see:  https://github.com/HotswapProjects/HotswapAgent/issues/41
      http://stackoverflow.com/questions/9588737/is-java-7-watchservice-slow-for-anyone-else/11182515#11182515

### CODE REVIEW

**Comment by derekchiang** [comment]
I'd be happy to merge this, but firstly can someone with access to a Mac verify that this works?

@thomasjm?  #3

**Comment by semperos** [comment]
Going to test this on my Mac, but as I mentioned to @mdpendergrass he'll need to handle the case where that `com.sun.nio.file.SensitivityWatchEventModifier` class isn't available, since it's JVM implementation-specific.

**Comment by derekchiang** [comment]
Yeah, using `com.sun.*` APIs definitely seems concerning.

**Comment by semperos** [comment]
I have verified in my own project that uses Clojure-Watch that @mdpendergrass 's changes drastically improve the performance on Mac OSX.

The Hotspot JVM is extremely popular, and given Mike's code falls back if the particular classes aren't present, I only see this as a win for the project. I vote :+1:

**Comment by derekchiang** [comment]
Cool, merged!  Will push to Clojars too.

**Comment by semperos** [comment]
Thanks @derekchiang for your work on the project and thanks @mdpendergrass for this PR!

**Pull request merged**
